# Generated by Django 5.2.8 on 2025-11-29 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_requirements', models.TextField(help_text='Enter the job description and requirements here.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cvs/')),
                ('candidate_name', models.CharField(blank=True, max_length=200, null=True)),
                ('candidate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('raw_text', models.TextField(blank=True)),
                ('evaluation_json', models.JSONField(blank=True, null=True)),
                ('fit_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='evaluator.jobdescription')),
            ],
        ),
    ]
